### ISSUE TITLE
Parser does not compile with happy 1.19.10

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3664]
Our stack snapshot specifies happy 1.19.9, which works fine. Attempting to compile purescript with the latest release of happy, namely 1.19.10, however, produces a number of errors along the lines of

```
dist/build/Language/PureScript/CST/Parser.hs:1137:53: error:
    Wildcard ‘_’ not allowed
      in the definition of data constructor ‘HappyWrap181’
     |
1137 | newtype HappyWrap181 = HappyWrap181 ([(SourceToken, _)])
     |    
```

(see #3654), which arise as a result of the the type annotations we have in Parser.y. I played around a bit with Parser.y, e.g. by using explicit forall or by removing some of the type annotations, but wasn't able to get it to compile. This might be a bug in happy.

This isn't particularly urgent; presumably we can just stay pinned to happy 1.19.9 if we need to. It might be nice to be able to take advantage of upstream improvements later on, though.

**Comment by natefaubion** [comment]
I don't see how an explicit forall can ever be used successfully in Happy because you'll always end up with a rank-n type, which isn't what you actually want.

The issue is with the parameterized productions like `delimited` and `manySep` which get stamped out for each application, so they aren't _actually_ polymorphic. This is why you needed to use `_` in the past, and this is something I actually picked up from the Happy documentation. If it no longer works, that sounds like a pretty serious issue.

**Comment by hdgarrood** [comment]
I'm not sure I understand what's going on here, but see https://github.com/simonmar/happy/pull/134 regarding explicit forall

**Comment by natefaubion** [comment]
> I'm not sure I understand what's going on here

The current issues stem from using [parameterized productions](https://www.haskell.org/happy/doc/html/sec-grammar.html#sec-param-prods) which are actually macros. When you do something like `manySep(foo)`, it actually expands that syntactically to productions with `foo` embedded in it. However you can only give a type signature to the parameterized production as a whole, and there's no way to instantiate the type signature for each application. So something like the following will result in type errors:

```
manySep(a) :: { forall x. [x] }
  : ...

foo :: { Foo }
  : ...

bar :: { Bar }
  : manySep(foo) { ... }
```

That's because calling `manySep(foo)` stamps out productions specialized to the `foo` production, and so the type of _that_ will be `[Foo]` and not `forall x. [x]` which is of course a type error. The work around has always been to just use wildcards `[_]`, and GHC will just infer it for whatever it stamps out. I'm not sure what that referenced PR actually does, but if it generated newtypes for every type signature it's going to break code.

**Comment by natefaubion** [comment]
The other workaround is to not use parameterized productions, and just manually expand them all.

**Comment by hdgarrood** [comment]
Makes sense, thank you!

**Comment by natefaubion** [comment]
Happy issue https://github.com/simonmar/happy/issues/141

**Comment by int-index** [comment]
It is unfortunate, but wildcards were never a feature supported in `happy`, see https://github.com/simonmar/happy/issues/141#issuecomment-498159812

PureScript should stop using them, regardless of `happy` version.

**Comment by natefaubion** [comment]
Turns out happy supports types for parameterized productions, but it's just undocumented. So this has a straightforward fix.

**Comment by arrowd** [comment]
I tried building PureScript with happy-1.19.11 and got following error:

```
/wrkdirs/usr/ports/lang/purescript/work/purescript-0.13.2/dist-newstyle/build/x86_64-freebsd/ghc-8.6.5/purescript-0.13.2/build/Language/PureScript/CST/Parser.hs:60:64: error:
    Not in scope: type variable ‘a’
   |
60 | newtype HappyWrap27 = HappyWrap27 (QualifiedName (N.ProperName a))
   |                                                                ^

/wrkdirs/usr/ports/lang/purescript/work/purescript-0.13.2/dist-newstyle/build/x86_64-freebsd/ghc-8.6.5/purescript-0.13.2/build/Language/PureScript/CST/Parser.hs:67:55: error:
    Not in scope: type variable ‘a’
   |
67 | newtype HappyWrap28 = HappyWrap28 (Name (N.ProperName a))
   |                                                       ^

```

Would it be possible to make PureScript support newest happy?

**Comment by hdgarrood** [comment]
Yeah seems like this is still an issue. I think it would be nice to be able to upgrade happy but please note that building the compiler with libraries/tools at versions other than those specified by stack.yaml is not supported.

**Comment by arrowd** [comment]
Just FYI, it also doesn't work with happy 1.19.12.
