### ISSUE TITLE
Build failure with protolude 0.2

### ISSUE THREAD

**Issue by ilovezfs** [purescript/purescript#3065]
See https://matrix.hackage.haskell.org/package/purescript where the build is failing across the board.

The only constraint for protolude in https://hackage.haskell.org/package/purescript-0.11.6/revision/0.cabal is `protolude >=0.1.6`.  However, PureScript is not yet compatible with protolude 0.2, which was uploaded to Hackage on August 8. So the build is now broken as follows:
```
[126 of 147] Compiling Language.PureScript.Ide.Filter ( src/Language/PureScript/Ide/Filter.hs, dist/dist-sandbox-e1083bf3/build/Language/PureScript/Ide/Filter.o )
[127 of 147] Compiling Language.PureScript.Ide.Matcher ( src/Language/PureScript/Ide/Matcher.hs, dist/dist-sandbox-e1083bf3/build/Language/PureScript/Ide/Matcher.o )
[128 of 147] Compiling Language.PureScript.Ide.Completion ( src/Language/PureScript/Ide/Completion.hs, dist/dist-sandbox-e1083bf3/build/Language/PureScript/Ide/Completion.o )

src/Language/PureScript/Ide/Completion.hs:41:3: error:
    Ambiguous occurrence ‘<&>’
    It could refer to either ‘Protolude.<&>’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                          or ‘Control.Lens.<&>’,
                             imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                             (and originally defined in ‘Control.Lens.Lens’)

src/Language/PureScript/Ide/Completion.hs:53:3: error:
    Ambiguous occurrence ‘<&>’
    It could refer to either ‘Protolude.<&>’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                          or ‘Control.Lens.<&>’,
                             imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                             (and originally defined in ‘Control.Lens.Lens’)

src/Language/PureScript/Ide/Completion.hs:54:3: error:
    Ambiguous occurrence ‘<&>’
    It could refer to either ‘Protolude.<&>’,
                             imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                          or ‘Control.Lens.<&>’,
                             imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                             (and originally defined in ‘Control.Lens.Lens’)
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
purescript-0.11.6-KS07bXGc78PIm5hM3hewc failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by ilovezfs** [comment]
Note that constraining protolude to < 0.2 works around the immediate issue, but that would be a problematic solution because it prevents PureScript from being able to build with GHC 8.2.1, as the only version of protolude that currently allows base 4.10.0.0 is protolude 0.2. (protolude 0.1.10 restricts base to `base >= 4.6  && <4.10`.)

**Comment by kRITZCREEK** [comment]
There are more dependencies that currently don't build with GHC 8.2, so I'd say we delay the bump to 0.2 until all of them work fine. Sorry, I mean to put in the < 0.2 constraint for protolude ages ago.

**Comment by ilovezfs** [comment]
Are you sure about that? I'm getting a successful build with 8.2.1 just by doing `--constraint=protolude<0.2 --allow-newer=protolude:base` so maybe you're going off of old information?

**Comment by kRITZCREEK** [comment]
@ilovezfs At least not until https://github.com/haskell-fswatch/win32-notify/pull/1 is merged.

**Comment by ilovezfs** [comment]
Bleh, Windows. OK :)

**Comment by ilovezfs** [comment]
or perhaps less daring, just `import           Protolude hiding ((<&>))`.

**Comment by ilovezfs** [comment]
@kRITZCREEK https://github.com/haskell-fswatch/win32-notify/pull/1 has been merged.

**Comment by ilovezfs** [comment]
Win32-notify-0.3.0.3 is now on Hackage. @kRITZCREEK are there other blockers to 8.2.1 support?

**Comment by kRITZCREEK** [comment]
@ilovezfs Oh, lovely. That's what it failed on for me the last time, so I'll try to build again later and get back to you.

**Comment by ilovezfs** [comment]
Thanks @kRITZCREEK! We're down to only 6 formulae in Homebrew that can't build with 8.2.1 and still need 8.0.2. Looking forward to seeing it be 5! Hehe
