### ISSUE TITLE
Build errors when importing purescript-as-a-library (from Hackage)

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript#3091]
I can `stack build` a Haskell project importing/referencing/depending-on `purescript` as a `library` only when I use a local copy of the current purescript repo. I prefer to use hackage repos for external deps however.

Adding `purescript-0.11.6` (the latest on both Hackage and npm *and* in this here `master` branch) to my project's `extra-deps` (and `pipes-http-1.0.5` because stack insisted), using the same `nightly` `resolver` as used in *this* repo (master branch), still fails with the below compilation errors that don't occur when using a local copy instead of a Hackage dep:

    [141 of 147] Compiling Language.PureScript.Ide.Completion ( src/Language/PureScript/Ide/Completion.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.0.2/build/Language/PureScript/Ide/Completion.o )
    
    /tmp/stack23983/purescript-0.11.6/src/Language/PureScript/Ide/Completion.hs:41:3: error:
        Ambiguous occurrence ‘<&>’
        It could refer to either ‘Protolude.<&>’,
                                 imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                              or ‘Control.Lens.<&>’,
                                 imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                                 (and originally defined in ‘Control.Lens.Lens’)
       |
    41 |   <&> completionFromMatch
       |   ^^^
    
    /tmp/stack23983/purescript-0.11.6/src/Language/PureScript/Ide/Completion.hs:53:3: error:
        Ambiguous occurrence ‘<&>’
        It could refer to either ‘Protolude.<&>’,
                                 imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                              or ‘Control.Lens.<&>’,
                                 imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                                 (and originally defined in ‘Control.Lens.Lens’)
       |
    53 |   <&> simpleExport
       |   ^^^
    
    /tmp/stack23983/purescript-0.11.6/src/Language/PureScript/Ide/Completion.hs:54:3: error:
        Ambiguous occurrence ‘<&>’
        It could refer to either ‘Protolude.<&>’,
                                 imported from ‘Protolude’ at src/Language/PureScript/Ide/Completion.hs:12:1-26
                              or ‘Control.Lens.<&>’,
                                 imported from ‘Control.Lens’ at src/Language/PureScript/Ide/Completion.hs:14:1-46
                                 (and originally defined in ‘Control.Lens.Lens’)
       |
    54 |   <&> completionFromMatch
       |   ^^^

**Comment by kRITZCREEK** [comment]
The tagged 0.11.6 version does not have an upper bound on protolude, but doesn't work with protolude-0.2.x.

You can either use the invocation in https://github.com/purescript/purescript/issues/3065#issuecomment-328505841, wait for a release, or use the current master.

The isse was fixed in: https://github.com/purescript/purescript/commit/2b10b06ee5b75373505d497d6dd7602680ad6efc so you could also backport that, if you need 0.11.6 compatibility.

**Comment by metaleap** [comment]
> wait for a release, or use the current master

Will do both. If a fix is already in for an upcoming release, cool
