### ISSUE TITLE
0.12.0-rc purescript-psci-support overlapping instances

### ISSUE THREAD

**Issue by aka-bash0r** [purescript/purescript#3345]
I compiled the latest source pre-release (0.12.0-rc) on a recent Gentoo Linux installation. When using `pulp init` to generate the project skeleton, pulp repl fails to start with the error message that instances for Eval are ambiguous. Full error message of a REPL run:
[log.txt](https://github.com/purescript/purescript/files/1966443/log.txt)
This was my first try to install purescript. I'm neither experienced with the language itself nor with its compiler infrastructure. Though, this looks like instance declarations are being considered overriding each other even though they aren't. The relevant source file is from the purescript-psci-support package:

    module PSCI.Support where

    import Prelude

    import Control.Monad.Eff (Eff)
    import Control.Monad.Eff.Console (CONSOLE, logShow)
    import Control.Monad.Eff.Unsafe (unsafeCoerceEff)

    -- | The `Eval` class captures those types which can be
    -- | evaluated in the REPL.
    -- |
    -- | There are (possibly overlapping) instances provided for
    -- | the `Eff` type constructor and any `Show`able types.
    class Eval a where
      eval :: a -> Eff (console :: CONSOLE) Unit

    instance evalShow :: Show a => Eval a where
      eval = logShow

    instance evalEff :: Eval a => Eval (Eff eff a) where
      eval x = do
        a <- unsafeCoerceEff x
        eval a

Putting comments in front of one of these instance declarations resolves the compilation error but introduces a runtime bug in REPL - evaluation does not happen.

Let me know if there's anything I can do to help debugging this issue.

**Comment by hdgarrood** [comment]
This is expected - the problem is that the version of psci-support that you have is designed to work with compilers in the 0.11.x series. There is a `compiler/0.12` branch in the psci-support repository which you could switch to and it would work. However, I’d recommend just switching to 0.11 instead: many libraries won’t yet work with the 0.12 rc, and for now the rc is basically only intended to be used by people working on the compiler or libraries, definitely not people who are new to the language.

This error is correct; these instances do overlap, because `Eff eff a` matches both instances.
