### ISSUE TITLE
Build error with http-client 0.5

### ISSUE THREAD

**Issue by felixonmars** [purescript/purescript#2237]
I am getting the following build error when building purescript with http-client 0.5:

```
[115 of 137] Compiling Language.PureScript.Ide.Pursuit ( src/Language/PureScript/Ide/Pursuit.hs, dist/build/Language/PureScript/Ide/Pursuit.o )

src/Language/PureScript/Ide/Pursuit.hs:50:9: error:
    • Couldn't match expected type ‘HttpException’
                  with actual type ‘HttpExceptionContent’
    • In the pattern: StatusCodeException {}
      In an equation for ‘handler’:
          handler (StatusCodeException {}) = pure []
```

**Comment by hdgarrood** [comment]
It should work with http-client 0.4, as that's what the Stackage snapshot is using. I guess we could also add some more restrictive upper bounds somewhere in the cabal file.

I wonder if we should add a little note into INSTALL.md saying that if you want to compile with cabal-install, we recommend using constraints from the cabal.config file for whichever LTS snapshot we're using from stackage.org: https://www.stackage.org/lts-6.7/cabal.config

**Comment by felixonmars** [comment]
I see. Stackage is moving to http-client 0.5 some time in the future, though: https://github.com/fpco/stackage/issues/1676

**Comment by hdgarrood** [comment]
Yes, in general I think it's safe to assume that everything on Stackage will get updated eventually. For purescript, it seems to make the most sense to just stick to Stackage LTS releases. So, once LTS 7 is out, and once we have a good reason to update or someone finds the time, we will update our stack.yaml and purescript.cabal, and also make any necessary code changes (such as this one).

**Comment by felixonmars** [comment]
I see. Thanks for the explanation :)
